// File gathering metadata-related functionality, whose purpose is to be #include'd by main.cc.
// The authorship and license information are in main.cc.

static int tifileutil_metadata_usage(int * argc, char *** argv)
{
	fprintf(stderr, R"x(Usage: %s metadata -m MODE [OPTIONS] [FILE | -]
Where MODE may be:
 gather:        print metadata from a file under a parsable "key": "value" form, with one
                pair per line (single, group, backup, flash and tigroup files are supported)
 apply:         apply metadata from the "key": "value" form generated by gather or a compatible tool
 get:           retrieve a single piece of metadata from a file.
 set:           set one or more pieces of metadata on a file.

Generic OPTIONS may include:
 -o FILE:     output result to FILE
 -v:          be verbose

OPTIONS for apply mode may include:
 -i FILE:     read metadata from FILE (default: stdin)

OPTIONS for get mode may include (a single option at a time):
 -n:            get on-calc variable name (TI-Z80, TI-eZ80, TI-68k)
 -f:            get on-calc folder name (TI-68k)
 -t:            get variable type as integer (TI-Z80, TI-eZ80, TI-68k)
 -h:            get file magic number (8 bytes)
 -V:            get file version (TI-Z80, TI-eZ80)
 -c:            get file comment
 -a:            get file archived information (TI-Z80, TI-eZ80, TI-68k)
 -l:            get file locked information (TI-68k)
 -x:            get stored data checksum and computed data checksum

OPTIONS for set mode may include (multiple options at a time):
 -n NAME:       set on-calc variable name to NAME (TI-Z80, TI-eZ80, TI-68k)
 -f NAME:       set on-calc folder name to NAME (TI-68k)
 -t TYPE:       set variable type to TYPE integer (TI-Z80, TI-eZ80, TI-68k)
 -h MAGIC:      set file magic number to MAGIC
 -V VERSION:    set file version to VERSION (TI-Z80, TI-eZ80)
 -c COMMENT:    set file comment to COMMENT (strftime format string)
 --raw-comment=COMMENT: set the file comment literally (no strftime expansion)
 -a 0/1:        set file archived information to 0/1 (TI-Z80, TI-eZ80, TI-68k)
 -l 0/1:        set file locked information to 0/1 (TI-68k) - note: archived implies locked
 -x VALUE|fix:  set stored data checksum to the given value, or compute the data checksum and set it as stored data checksum.
Note: all options must precede the file name(s).
)x", (*argv)[0]);
	return 1;
}

static int tifileutil_metadata_gather(int * argc, char *** argv, unsigned int offset)
{
	int ret = 3;

	const char * infilename = nullptr;
	char * outfilename = nullptr;
	int verbose = 0;
	TifilesMetadataPair * pairs = nullptr;
	FILE * outfile = stdout;
	unsigned int i;
	unsigned int first_file = 0;

	int j;

	for (i = offset + 2; i < (unsigned int)*argc; i++) {
		if ((*argv)[i][0] == '-' && (*argv)[i][1]) {
			for (j = 1; (*argv)[i][j]; j++) {
				switch ((*argv)[i][j]) {
					case 'm':
						// The metadata mode, already handled by the dispatcher.
						GET_OPTION_ARG_IGNORE("-m", tifileutil_metadata_usage);
					break;

					case 'o':
						GET_OPTION_ARG(outfilename, "-o", tifileutil_metadata_usage);
					break;

					case 'v':
						verbose = 1;
					break;

					default:
						tifileutil_critical(_("%s: unknown option -%c."), (*argv)[0], (*argv)[i][j]);
					return tifileutil_metadata_usage(argc, argv);
				}
			}
		}
		else {
			first_file = i;
			break;
		}
	}

	if (!first_file) {
		return tifileutil_metadata_usage(argc, argv);
	}
	infilename = (const char *)(*argv)[first_file];

	pairs = tifiles_file_get_metadata(infilename);
	if (!pairs) {
		tifileutil_critical(_("%s: cannot read metadata from %s."), (*argv)[0], infilename);
		goto end;
	}

	if (outfilename) {
		outfile = fopen(outfilename, "wb");
		if (!outfile) {
			perror(outfilename);
			ret = 2;
			goto end;
		}
	}

	for (i = 0; pairs && pairs[i].key != nullptr; i++) {
		fprintf(outfile, "\"%s\": \"%s\"\n", pairs[i].key, pairs[i].value);
	}

	if (verbose) {
		tifileutil_info(_("%s: wrote %u metadata pairs for %s."), (*argv)[0], i, infilename);
	}

	ret = 0;

end:
	if (outfile && outfile != stdout) {
		fclose(outfile);
	}
	if (pairs) {
		tifiles_metadata_free(pairs);
	}

	return ret;
}

// Check that a tigroup member name is safe to use as a plain file name.
static int tifileutil_member_name_unsafe(const char * name);

// Parse an "entry[N].suffix" key; return 1 on success.
static int tifileutil_metadata_entry_key(const char * key, unsigned int * entry, const char ** suffix)
{
	const char * p;
	char * end;

	if (strncmp(key, "entry[", 6)) {
		return 0;
	}
	p = strchr(key + 6, ']');
	if (!p) {
		return 0;
	}
	unsigned long n = strtoul(key + 6, &end, 10);
	if (end != p || n < 1 || n > 65535) {
		return 0;
	}
	*entry = (unsigned int)n;
	*suffix = (p[1] == '.') ? p + 2 : nullptr;
	return 1;
}

// A variable type is valid for the model when its extension is known: the
// library returns a "??"-style fallback (or nullptr) for unknown types.
static int tifileutil_metadata_type_valid(CalcModel model, uint8_t type)
{
	const char * ext = tifiles_vartype2fext(model, type);
	size_t len = ext ? strlen(ext) : 0;

	return (ext && len > 0 && ext[len - 1] != '?');
}

// Apply a single pair to a variable entry of a regular file, or of a tigroup
// member; the name, folder, type, version and attribute keys are supported.
// Return 0 on success, non-zero on error (message already printed).
static int tifileutil_metadata_set_var_entry(char *** argv, CalcModel model, VarEntry * ve, const char * key, const char * value)
{
	if (!strcmp(key, "name")) {
		size_t len = strlen(value);
		if (len == 0 || len > 8) {
			tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
			return 1;
		}
		strncpy(ve->name, value, sizeof(ve->name) - 1);
		ve->name[sizeof(ve->name) - 1] = 0;
		return 0;
	}
	if (!strcmp(key, "folder")) {
		if (ticonv_model_is_ti68k(model)) {
			if (strlen(value) > 8) {
				tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
				return 1;
			}
			strncpy(ve->folder, value, sizeof(ve->folder) - 1);
			ve->folder[sizeof(ve->folder) - 1] = 0;
		}
		else if (value[0]) {
			tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, tifiles_model_to_string(model));
			return 1;
		}
		return 0;
	}
	if (!strcmp(key, "type")) {
		char * end;
		unsigned long v = strtoul(value, &end, 0);
		if (*end || v > 0xFF || !tifileutil_metadata_type_valid(model, (uint8_t)v)) {
			tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
			return 1;
		}
		ve->type = (uint8_t)v;
		return 0;
	}
	if (!strcmp(key, "version")) {
		char * end;
		unsigned long v = strtoul(value, &end, 0);
		if (*end || v > 0xFF) {
			tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
			return 1;
		}
		ve->version = (uint8_t)v;
		return 0;
	}
	if (!strcmp(key, "attr.archived")) {
		if (!strcmp(value, "0")) {
			if (ve->attr == ATTRB_ARCHIVED) {
				ve->attr = ATTRB_NONE;
			}
			return 0;
		}
		if (!strcmp(value, "1")) {
			if (!tifiles_has_attrs(model)) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, tifiles_model_to_string(model));
				return 1;
			}
			ve->attr = ATTRB_ARCHIVED;
			return 0;
		}
		tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
		return 1;
	}
	if (!strcmp(key, "attr.locked")) {
		if (!strcmp(value, "0")) {
			if (ve->attr != ATTRB_ARCHIVED) {
				ve->attr = ATTRB_NONE;
			}
			return 0;
		}
		if (!strcmp(value, "1")) {
			if (!ticonv_model_is_ti68k(model)) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, tifiles_model_to_string(model));
				return 1;
			}
			ve->attr = (ve->attr == ATTRB_ARCHIVED) ? ATTRB_ARCHIVED : ATTRB_LOCKED;
			return 0;
		}
		tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
		return 1;
	}
	tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
	return 1;
}

// Entry-level keys which cannot be set.
static int tifileutil_metadata_entry_key_readonly(const char * suffix)
{
	return (!strcmp(suffix, "type.name") || !strcmp(suffix, "type.ext") || !strcmp(suffix, "size"));
}

// File-level keys which cannot be set.
static int tifileutil_metadata_file_key_readonly(const char * key)
{
	return (!strcmp(key, "file.model") || !strcmp(key, "file.entries")
	     || !strcmp(key, "file.checksum.computed") || !strcmp(key, "metadata.version"));
}

// Store the given checksum into the last 2 bytes of the file.
static int tifileutil_metadata_patch_checksum(const char * filename, uint16_t checksum)
{
	FILE * f = fopen(filename, "r+b");
	int ret;

	if (!f) {
		return 1;
	}
	ret = (fseek(f, -2, SEEK_END) < 0
	    || fputc(checksum & 0xff, f) == EOF
	    || fputc((checksum >> 8) & 0xff, f) == EOF);
	fclose(f);
	return ret;
}

// Apply a list of key/value pairs to a TI file, then write it back; the
// pairs use the gather interchange format. Return 0 on success, non-zero on
// error (message already printed). @fixchecksum requests recomputing the
// stored checksum, which the writers do anyway; it is rejected for file
// classes without a checksum.
static int tifileutil_metadata_apply_pairs(char *** argv, const char * infilename, const char * outfilename, TifilesMetadataPair * pairs, int fixchecksum)
{
	FileClass fc = tifiles_file_get_class(infilename);
	CalcModel model = tifiles_file_get_model(infilename);
	uint16_t stored_checksum = 0;
	int set_stored_checksum = 0;
	int ret = 0;
	unsigned int i;

	if (fc & TIFILE_REGULAR) {
		FileContent * content = tifiles_content_create_regular(model);

		if (!content) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			return 1;
		}
		ret = err_print(argv, "tifiles_file_read_regular", tifiles_file_read_regular(infilename, content));
		if (ret) {
			tifiles_content_delete_regular(content);
			return 1;
		}
		for (i = 0; pairs && pairs[i].key != nullptr; i++) {
			const char * key = pairs[i].key;
			const char * value = pairs[i].value;
			unsigned int entry;
			const char * suffix;

			if (!strcmp(key, "file.class")) {
				const char * current = (content->num_entries == 1) ? "single" : "group";

				if (strcmp(value, current)) {
					tifileutil_critical(_("%s: cannot change the class of %s: the metadata key file.class cannot be set to %s for a %s file."), (*argv)[0], infilename, value, current);
					ret = 1;
					break;
				}
				continue;
			}
			if (!strcmp(key, "file.comment")) {
				strncpy(content->comment, value, sizeof(content->comment) - 1);
				content->comment[sizeof(content->comment) - 1] = 0;
			}
			else if (!strcmp(key, "file.checksum.stored")) {
				char * end;
				unsigned long v = strtoul(value, &end, 0);
				if (*end || v > 0xFFFF) {
					tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
					ret = 1;
					break;
				}
				if (!ticonv_model_is_ti68k(model)) {
					// The global checksum is stored in the last 2 bytes of the file.
					stored_checksum = (uint16_t)v;
					set_stored_checksum = 1;
				}
				else if (v != content->stored_checksum) {
					// TI-68k regular files have per-entry checksums only.
					tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, tifiles_model_to_string(model));
					ret = 1;
					break;
				}
			}
			else if (!strcmp(key, "file.magic")) {
				if (strlen(value) != 8 || tifiles_signature2calctype(value) != content->model) {
					tifileutil_critical(_("%s: the magic %s does not match the model of %s."), (*argv)[0], value, infilename);
					ret = 1;
					break;
				}
			}
			else if (tifileutil_metadata_entry_key(key, &entry, &suffix)) {
				if (suffix && tifileutil_metadata_entry_key_readonly(suffix)) {
					tifileutil_critical(_("%s: the metadata key %s cannot be set."), (*argv)[0], key);
					ret = 1;
					break;
				}
				if (!suffix || entry > content->num_entries) {
					tifileutil_critical(_("%s: entry %u does not exist in %s."), (*argv)[0], entry, infilename);
					ret = 1;
					break;
				}
				if (tifileutil_metadata_set_var_entry(argv, content->model, content->entries[entry - 1], suffix, value)) {
					ret = 1;
					break;
				}
			}
			else if (tifileutil_metadata_file_key_readonly(key)) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set."), (*argv)[0], key);
				ret = 1;
				break;
			}
			else {
				tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
				ret = 1;
				break;
			}
		}
		if (!ret) {
			ret = err_print(argv, "tifiles_file_write_regular", tifiles_file_write_regular(outfilename, content, 0));
		}
		tifiles_content_delete_regular(content);
		if (ret || !set_stored_checksum) {
			return ret ? 1 : 0;
		}
		if (tifileutil_metadata_patch_checksum(outfilename, stored_checksum)) {
			tifileutil_critical(_("%s: cannot write the stored checksum to %s."), (*argv)[0], outfilename);
			return 1;
		}
		return 0;
	}
	if (fc == TIFILE_BACKUP) {
		BackupContent * content = tifiles_content_create_backup(model);
		const char * current = "backup";

		if (!content) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			return 1;
		}
		ret = err_print(argv, "tifiles_file_read_backup", tifiles_file_read_backup(infilename, content));
		if (ret) {
			tifiles_content_delete_backup(content);
			return 1;
		}
		for (i = 0; pairs && pairs[i].key != nullptr; i++) {
			const char * key = pairs[i].key;
			const char * value = pairs[i].value;
			unsigned int entry;
			const char * suffix;

			if (!strcmp(key, "file.class")) {
				if (strcmp(value, current)) {
					tifileutil_critical(_("%s: cannot change the class of %s: the metadata key file.class cannot be set to %s for a %s file."), (*argv)[0], infilename, value, current);
					ret = 1;
					break;
				}
				continue;
			}
			if (!strcmp(key, "file.comment")) {
				strncpy(content->comment, value, sizeof(content->comment) - 1);
				content->comment[sizeof(content->comment) - 1] = 0;
			}
			else if (!strcmp(key, "file.checksum.stored")) {
				char * end;
				unsigned long v = strtoul(value, &end, 0);
				if (*end || v > 0xFFFF) {
					tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
					ret = 1;
					break;
				}
				stored_checksum = (uint16_t)v;
				set_stored_checksum = 1;
			}
			else if (tifileutil_metadata_entry_key(key, &entry, &suffix) || tifileutil_metadata_file_key_readonly(key)) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, "backup");
				ret = 1;
				break;
			}
			else {
				tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
				ret = 1;
				break;
			}
		}
		if (!ret) {
			ret = err_print(argv, "tifiles_file_write_backup", tifiles_file_write_backup(outfilename, content));
		}
		tifiles_content_delete_backup(content);
		if (ret || !set_stored_checksum) {
			return ret ? 1 : 0;
		}
		if (tifileutil_metadata_patch_checksum(outfilename, stored_checksum)) {
			tifileutil_critical(_("%s: cannot write the stored checksum to %s."), (*argv)[0], outfilename);
			return 1;
		}
		return 0;
	}
	if (fc == TIFILE_FLASH) {
		FlashContent * content = tifiles_content_create_flash(model);
		const char * current = "flash";

		if (!content) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			return 1;
		}
		ret = err_print(argv, "tifiles_file_read_flash", tifiles_file_read_flash(infilename, content));
		if (ret) {
			tifiles_content_delete_flash(content);
			return 1;
		}
		for (i = 0; pairs && pairs[i].key != nullptr; i++) {
			const char * key = pairs[i].key;
			const char * value = pairs[i].value;
			unsigned int entry;
			const char * suffix;

			if (!strcmp(key, "file.class")) {
				if (strcmp(value, current)) {
					tifileutil_critical(_("%s: cannot change the class of %s: the metadata key file.class cannot be set to %s for a %s file."), (*argv)[0], infilename, value, current);
					ret = 1;
					break;
				}
				continue;
			}
			if (!strcmp(key, "file.name")) {
				if (strlen(value) == 0 || strlen(value) > 8) {
					tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
					ret = 1;
					break;
				}
				strncpy(content->name, value, sizeof(content->name) - 1);
				content->name[sizeof(content->name) - 1] = 0;
			}
			else if (tifileutil_metadata_entry_key(key, &entry, &suffix) || tifileutil_metadata_file_key_readonly(key)) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, "flash");
				ret = 1;
				break;
			}
			else {
				tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
				ret = 1;
				break;
			}
		}
		if (fixchecksum) {
			tifileutil_critical(_("%s: cannot fix the checksum of %s files."), (*argv)[0], "flash");
			ret = 1;
		}
		if (!ret) {
			ret = err_print(argv, "tifiles_file_write_flash", tifiles_file_write_flash(outfilename, content));
		}
		tifiles_content_delete_flash(content);
		return ret ? 1 : 0;
	}
	if (fc == TIFILE_TIGROUP) {
		TigContent * content = tifiles_content_create_tigroup(CALC_NONE, 0);
		const char * current = "tigroup";

		if (!content) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			return 1;
		}
		ret = err_print(argv, "tifiles_file_read_tigroup", tifiles_file_read_tigroup(infilename, content));
		if (ret) {
			tifiles_content_delete_tigroup(content);
			return 1;
		}
		for (i = 0; pairs && pairs[i].key != nullptr; i++) {
			const char * key = pairs[i].key;
			const char * value = pairs[i].value;
			unsigned int entry;
			const char * suffix;

			if (!strcmp(key, "file.class")) {
				if (strcmp(value, current)) {
					tifileutil_critical(_("%s: cannot change the class of %s: the metadata key file.class cannot be set to %s for a %s file."), (*argv)[0], infilename, value, current);
					ret = 1;
					break;
				}
				continue;
			}
			if (tifileutil_metadata_entry_key(key, &entry, &suffix)) {
				if (!suffix || entry > content->n_vars + content->n_apps) {
					tifileutil_critical(_("%s: entry %u does not exist in %s."), (*argv)[0], entry, infilename);
					ret = 1;
					break;
				}
				if (entry <= content->n_vars) {
					TigEntry * te = content->var_entries[entry - 1];

					if (!strcmp(suffix, "filename")) {
						if (tifileutil_member_name_unsafe(value)) {
							tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
							ret = 1;
							break;
						}
						char * newname = strdup(value);
						if (!newname) {
							tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
							ret = 1;
							break;
						}
						g_free(te->filename);
						te->filename = newname;
					}
					else if (tifileutil_metadata_entry_key_readonly(suffix)) {
						tifileutil_critical(_("%s: the metadata key %s cannot be set."), (*argv)[0], key);
						ret = 1;
						break;
					}
					else {
						// Degenerate members (regular files with no variable
						// entry) carry no variable to modify.
						VarEntry * ve = (te->content.regular && te->content.regular->num_entries) ? te->content.regular->entries[0] : nullptr;
						if (!ve) {
							tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, "tigroup");
							ret = 1;
							break;
						}
						if (tifileutil_metadata_set_var_entry(argv, content->model, ve, suffix, value)) {
							ret = 1;
							break;
						}
					}
				}
				else {
					// Flash member: the member name and the application name.
					TigEntry * te = content->app_entries[entry - content->n_vars - 1];

					if (!strcmp(suffix, "filename")) {
						if (tifileutil_member_name_unsafe(value)) {
							tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
							ret = 1;
							break;
						}
						char * newname = strdup(value);
						if (!newname) {
							tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
							ret = 1;
							break;
						}
						g_free(te->filename);
						te->filename = newname;
					}
					else if (!strcmp(suffix, "name")) {
						if (strlen(value) == 0 || strlen(value) > 8) {
							tifileutil_critical(_("%s: invalid value %s for key %s."), (*argv)[0], value, key);
							ret = 1;
							break;
						}
						strncpy(te->content.flash->name, value, sizeof(te->content.flash->name) - 1);
						te->content.flash->name[sizeof(te->content.flash->name) - 1] = 0;
					}
					else if (tifileutil_metadata_entry_key_readonly(suffix)) {
						tifileutil_critical(_("%s: the metadata key %s cannot be set."), (*argv)[0], key);
						ret = 1;
						break;
					}
					else {
						tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
						ret = 1;
						break;
					}
				}
			}
			else if (tifileutil_metadata_file_key_readonly(key) || !strcmp(key, "file.comment") || !strcmp(key, "file.checksum.stored") || !strcmp(key, "file.name")) {
				tifileutil_critical(_("%s: the metadata key %s cannot be set for %s files."), (*argv)[0], key, "tigroup");
				ret = 1;
				break;
			}
			else {
				tifileutil_critical(_("%s: unknown metadata key %s."), (*argv)[0], key);
				ret = 1;
				break;
			}
		}
		if (fixchecksum) {
			tifileutil_critical(_("%s: cannot fix the checksum of %s files."), (*argv)[0], "tigroup");
			ret = 1;
		}
		if (!ret) {
			ret = err_print(argv, "tifiles_file_write_tigroup", tifiles_file_write_tigroup(outfilename, content));
		}
		tifiles_content_delete_tigroup(content);
		return ret ? 1 : 0;
	}
	tifileutil_critical(_("%s: cannot read metadata from %s."), (*argv)[0], infilename);
	return 1;
}

static int tifileutil_metadata_get(int * argc, char *** argv, unsigned int offset)
{
	int ret = 3;

	const char * infilename = nullptr;
	unsigned int first_file = 0;
	int nopts = 0;
	const char * key = nullptr;
	TifilesMetadataPair * pairs = nullptr;

	int j;

	for (unsigned int i = offset + 2; i < (unsigned int)*argc; i++) {
		if ((*argv)[i][0] == '-' && (*argv)[i][1]) {
			for (j = 1; (*argv)[i][j]; j++) {
				switch ((*argv)[i][j]) {
					case 'm':
						// The metadata mode, already handled by the dispatcher.
						GET_OPTION_ARG_IGNORE("-m", tifileutil_metadata_usage);
					break;

					case 'n': key = "entry[1].name"; nopts++; break;
					case 'f': key = "entry[1].folder"; nopts++; break;
					case 't': key = "entry[1].type"; nopts++; break;
					case 'h': key = "file.magic"; nopts++; break;
					case 'V': key = "entry[1].version"; nopts++; break;
					case 'c': key = "file.comment"; nopts++; break;
					case 'a': key = "entry[1].attr.archived"; nopts++; break;
					case 'l': key = "entry[1].attr.locked"; nopts++; break;
					case 'x': key = "checksums"; nopts++; break;

					default:
						tifileutil_critical(_("%s: unknown option -%c."), (*argv)[0], (*argv)[i][j]);
					return tifileutil_metadata_usage(argc, argv);
				}
			}
		}
		else {
			first_file = i;
			break;
		}
	}
	if (nopts == 0) {
		tifileutil_critical(_("%s: no option specified for get."), (*argv)[0]);
		return tifileutil_metadata_usage(argc, argv);
	}
	if (nopts > 1) {
		tifileutil_critical(_("%s: multiple options specified for get."), (*argv)[0]);
		return tifileutil_metadata_usage(argc, argv);
	}
	if (!first_file) {
		return tifileutil_metadata_usage(argc, argv);
	}
	infilename = (const char *)(*argv)[first_file];

	pairs = tifiles_file_get_metadata(infilename);
	if (!pairs) {
		tifileutil_critical(_("%s: cannot read metadata from %s."), (*argv)[0], infilename);
		goto end;
	}
	if (!strcmp(key, "checksums")) {
		TifilesMetadataPair * computed = tifiles_metadata_find_pair(pairs, "file.checksum.computed");
		TifilesMetadataPair * stored = tifiles_metadata_find_pair(pairs, "file.checksum.stored");

		if (!computed || !stored) {
			tifileutil_critical(_("%s: the metadata key %s is not present in %s."), (*argv)[0], "file.checksum.stored", infilename);
			goto end;
		}
		printf("%s %s\n", computed->value, stored->value);
	}
	else {
		TifilesMetadataPair * pair = tifiles_metadata_find_pair(pairs, key);

		if (!pair) {
			tifileutil_critical(_("%s: the metadata key %s is not present in %s."), (*argv)[0], key, infilename);
			goto end;
		}
		printf("%s\n", pair->value);
	}
	ret = 0;

end:
	if (pairs) {
		tifiles_metadata_free(pairs);
	}

	return ret;
}

static int tifileutil_metadata_set(int * argc, char *** argv, unsigned int offset)
{
	int ret = 3;

	const char * infilename = nullptr;
	char * outfilename = nullptr;
	unsigned int first_file = 0;
	int verbose = 0;
	int fixchecksum = 0;
	int rawcomment = 0;
	const char * comment = nullptr;
	const char * varname = nullptr;
	const char * foldername = nullptr;
	const char * typestr = nullptr;
	const char * magicstr = nullptr;
	const char * versionstr = nullptr;
	const char * attrarch = nullptr;
	const char * attrlock = nullptr;
	const char * checksumstr = nullptr;
	TifilesMetadataPair * pairs = nullptr;
	unsigned int count = 0;
	char commentbuf[80];
	int nopts = 0;

	int j;

	for (unsigned int i = offset + 2; i < (unsigned int)*argc; i++) {
		if ((*argv)[i][0] == '-' && (*argv)[i][1]) {
			// The long-form option sets the comment literally, without the
			// strftime expansion of -c; the last option given wins.
			if (!strncmp((*argv)[i], "--raw-comment", 13)) {
				rawcomment = 1;
				GET_LONG_OPTION_ARG(comment, "--raw-comment", tifileutil_metadata_usage);
				continue;
			}
			for (j = 1; (*argv)[i][j]; j++) {
				switch ((*argv)[i][j]) {
					case 'm':
						// The metadata mode, already handled by the dispatcher.
						GET_OPTION_ARG_IGNORE("-m", tifileutil_metadata_usage);
					break;

					case 'n':
						GET_OPTION_ARG(varname, "-n", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'f':
						GET_OPTION_ARG(foldername, "-f", tifileutil_metadata_usage);
						nopts++;
					break;

					case 't':
						GET_OPTION_ARG(typestr, "-t", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'h':
						GET_OPTION_ARG(magicstr, "-h", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'V':
						GET_OPTION_ARG(versionstr, "-V", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'c':
						rawcomment = 0;
						GET_OPTION_ARG(comment, "-c", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'a':
						GET_OPTION_ARG(attrarch, "-a", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'l':
						GET_OPTION_ARG(attrlock, "-l", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'x':
						GET_OPTION_ARG(checksumstr, "-x", tifileutil_metadata_usage);
						nopts++;
					break;

					case 'v':
						verbose = 1;
					break;

					default:
						tifileutil_critical(_("%s: unknown option -%c."), (*argv)[0], (*argv)[i][j]);
					return tifileutil_metadata_usage(argc, argv);
				}
			}
		}
		else {
			first_file = i;
			break;
		}
	}

	if (nopts == 0) {
		tifileutil_critical(_("%s: no option specified for set."), (*argv)[0]);
		return tifileutil_metadata_usage(argc, argv);
	}
	if (!first_file) {
		return tifileutil_metadata_usage(argc, argv);
	}
	infilename = (const char *)(*argv)[first_file];

	// Build the pairs from the options; the strftime expansion of -c happens
	// here, in the option layer, while --raw-comment and apply stay literal.
	if (comment) {
		// The strftime expansion of -c happens in the option layer, while
		// --raw-comment and apply stay literal.
		tifileutil_comment_set(commentbuf, sizeof(commentbuf), comment, rawcomment);
		if (tifiles_metadata_add_pair(&pairs, &count, "file.comment", commentbuf)) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			goto end;
		}
	}
	if (varname && tifiles_metadata_add_pair(&pairs, &count, "entry[1].name", varname)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (foldername && tifiles_metadata_add_pair(&pairs, &count, "entry[1].folder", foldername)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (typestr && tifiles_metadata_add_pair(&pairs, &count, "entry[1].type", typestr)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (magicstr && tifiles_metadata_add_pair(&pairs, &count, "file.magic", magicstr)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (versionstr && tifiles_metadata_add_pair(&pairs, &count, "entry[1].version", versionstr)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (attrarch && tifiles_metadata_add_pair(&pairs, &count, "entry[1].attr.archived", attrarch)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (attrlock && tifiles_metadata_add_pair(&pairs, &count, "entry[1].attr.locked", attrlock)) {
		tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
		goto end;
	}
	if (checksumstr) {
		if (!strcmp(checksumstr, "fix")) {
			fixchecksum = 1;
		}
		else if (tifiles_metadata_add_pair(&pairs, &count, "file.checksum.stored", checksumstr)) {
			tifileutil_critical(_("%s: cannot allocate memory."), (*argv)[0]);
			goto end;
		}
	}

	if (tifileutil_metadata_apply_pairs(argv, infilename, outfilename ? outfilename : infilename, pairs, fixchecksum)) {
		goto end;
	}
	if (verbose) {
		tifileutil_info(_("%s: applied %u metadata pairs to %s."), (*argv)[0], count, infilename);
	}
	ret = 0;

end:
	if (pairs) {
		for (unsigned int i = 0; pairs[i].key != nullptr; i++) {
			free(pairs[i].key);
			free(pairs[i].value);
		}
		free(pairs);
	}

	return ret;
}

// Parse a "key": "value" line; the key is delimited by its quotes, and the
// value by the first and last quotes of the line, so that values containing
// quotes are tolerated. Return 1 on success.
static int tifileutil_metadata_parse_line(char * line, const char ** key, const char ** value)
{
	char * p = line;
	char * q;

	while (*p == ' ' || *p == '\t') {
		p++;
	}
	if (*p != '"') {
		return 0;
	}
	q = strchr(p + 1, '"');
	if (!q) {
		return 0;
	}
	*q = 0;
	*key = p + 1;
	p = q + 1;
	while (*p == ' ' || *p == '\t') {
		p++;
	}
	if (*p != ':') {
		return 0;
	}
	p++;
	while (*p == ' ' || *p == '\t') {
		p++;
	}
	if (*p != '"') {
		return 0;
	}
	q = strrchr(p + 1, '"');
	if (!q) {
		return 0;
	}
	*q = 0;
	*value = p + 1;
	return 1;
}

static int tifileutil_metadata_apply(int * argc, char *** argv, unsigned int offset)
{
	int ret = 3;

	const char * infilename = nullptr;
	const char * metadatafile = nullptr;
	char * outfilename = nullptr;
	unsigned int first_file = 0;
	int verbose = 0;
	FILE * metafile = stdin;
	TifilesMetadataPair * pairs = nullptr;
	unsigned int count = 0, lineno = 0;
	int seen_version = 0;
	char line[4096];

	int j;

	for (unsigned int i = offset + 2; i < (unsigned int)*argc; i++) {
		if ((*argv)[i][0] == '-' && (*argv)[i][1]) {
			for (j = 1; (*argv)[i][j]; j++) {
				switch ((*argv)[i][j]) {
					case 'm':
						// The metadata mode, already handled by the dispatcher.
						GET_OPTION_ARG_IGNORE("-m", tifileutil_metadata_usage);
					break;

					case 'i':
						GET_OPTION_ARG(metadatafile, "-i", tifileutil_metadata_usage);
					break;

					case 'o':
						GET_OPTION_ARG(outfilename, "-o", tifileutil_metadata_usage);
					break;

					case 'v':
						verbose = 1;
					break;

					default:
						tifileutil_critical(_("%s: unknown option -%c."), (*argv)[0], (*argv)[i][j]);
					return tifileutil_metadata_usage(argc, argv);
				}
			}
		}
		else {
			first_file = i;
			break;
		}
	}
	if (!first_file) {
		return tifileutil_metadata_usage(argc, argv);
	}
	infilename = (const char *)(*argv)[first_file];

	if (metadatafile) {
		metafile = fopen(metadatafile, "rt");
		if (!metafile) {
			perror(metadatafile);
			ret = 2;
			goto end;
		}
	}

	// Parse the metadata stream; the first line must be the metadata.version
	// pair, whose value is the version of the interchange format.
	while (fgets(line, sizeof(line), metafile)) {
		const char * key, * value;

		lineno++;
		if (!tifileutil_metadata_parse_line(line, &key, &value)) {
			tifileutil_critical(_("%s: cannot parse metadata line %u."), (*argv)[0], lineno);
			goto end;
		}
		if (count == 0 && !seen_version) {
			seen_version = 1;
			if (strcmp(key, "metadata.version")) {
				tifileutil_critical(_("%s: missing metadata.version key."), (*argv)[0]);
				goto end;
			}
			if (strcmp(value, "1")) {
				tifileutil_critical(_("%s: unsupported metadata version %s."), (*argv)[0], value);
				goto end;
			}
			continue;
		}
		if (tifiles_metadata_add_pair(&pairs, &count, key, value)) {
			// The error codes of the metadata API are not part of the public
			// API: report both possible failure causes.
			tifileutil_critical(_("%s: cannot add the metadata pair %s: out of memory or already present."), (*argv)[0], key);
			goto end;
		}
	}
	if (!seen_version) {
		tifileutil_critical(_("%s: missing metadata.version key."), (*argv)[0]);
		goto end;
	}

	if (tifileutil_metadata_apply_pairs(argv, infilename, outfilename ? outfilename : infilename, pairs, 0)) {
		goto end;
	}
	if (verbose) {
		tifileutil_info(_("%s: applied %u metadata pairs to %s."), (*argv)[0], count, infilename);
	}
	ret = 0;

end:
	if (metafile && metafile != stdin) {
		fclose(metafile);
	}
	if (pairs) {
		for (unsigned int i = 0; pairs[i].key != nullptr; i++) {
			free(pairs[i].key);
			free(pairs[i].value);
		}
		free(pairs);
	}

	return ret;
}

static int tifileutil_metadata(int * argc, char *** argv, unsigned int offset)
{
	const char * modestr = nullptr;

	int i, j;

	for (i = offset + 2; i < *argc; i++) {
		if ((*argv)[i][0] == '-' && (*argv)[i][1]) {
			for (j = 1; (*argv)[i][j]; j++) {
				switch ((*argv)[i][j]) {
					case 'm':
						GET_OPTION_ARG(modestr, "-m", tifileutil_metadata_usage);
					break;

					default:
						// Other options are handled by the sub-modes.
					break;
				}
			}
		}
		else {
			// All options must precede the file names.
			break;
		}
	}

	if (!modestr) {
		return tifileutil_metadata_usage(argc, argv);
	}
	if (!strcmp(modestr, "gather")) {
		return tifileutil_metadata_gather(argc, argv, offset);
	}
	if (!strcmp(modestr, "apply")) {
		return tifileutil_metadata_apply(argc, argv, offset);
	}
	if (!strcmp(modestr, "get")) {
		return tifileutil_metadata_get(argc, argv, offset);
	}
	if (!strcmp(modestr, "set")) {
		return tifileutil_metadata_set(argc, argv, offset);
	}
	tifileutil_critical(_("%s: unknown metadata mode %s."), (*argv)[0], modestr);
	return tifileutil_metadata_usage(argc, argv);
}
