;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; TI-84+ USB ROM Dumper
;;;
;;; Copyright (c) 2009, 2010 Brandon Wilson
;;; Copyright (c) 2012, 2013 Benjamin Moody
;;;
;;; This program is free software; you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 2 of the License, or
;;; (at your option) any later version.
;;; 
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;; 
;;; You should have received a copy of the GNU General Public License
;;; along with this program; if not, write to the Free Software Foundation,
;;; Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


.macro B_CALL arg
    rst 0x28
    .word \arg
    .endm
.ifdef TI84P
_LdHLind = 0x4009
_cphlde = 0x400C
_PutC = 0x4504
_PutS = 0x450A
_clrLCDFull = 0x4540
_homeUp = 0x4558
_runIndicOff = 0x4570
_Mov18B = 0x47DA
_getKey = 0x4972
_GetBaseVer = 0x4C6F
_GetVariableData = 0x5092
_SendUSBData = 0x50F2
_KillUSBDevice = 0x5257
_GetBootVer = 0x80B7
_GetHWVer = 0x80BA
_WriteAByteSafe = 0x80C6
_KillUSB = 0x810E

appData = 0x8000
ramCode = 0x8100
arcInfo = 0x83EE
curRow = 0x844B
OP1 = 0x8478
iMathPtr5 = 0x84DB
flags = 0x89F0
pagedCount = 0x9834
pagedBuf = 0x983A
appBackUpScreen = 0x9872
userMem = 0x9D95

outPageNum = 0x83EB
inputBuffer = 0x9C31
usbReadCount = 0x9C80
usbQueuedCount = 0x9C27

.macro SAVE_MEM_PAGE
        in a,(6)
        push af
.endm

.macro RESTORE_MEM_PAGE
        pop af
        out (6),a
.endm
.macro RESTORE_MEM_PAGE_SAVEF
        pop bc
        ld a,b
        out (6),a
.endm
.macro SET_FLASH_PAGE_A
        out (6), a
.endm
.endif

.ifdef TI84PC
_LdHLind = 0x4009
_cphlde = 0x400C
_PutC = 0x44FB
_PutS = 0x4501
_clrLCDFull = 0x4537
_homeUp = 0x454F
_runIndicOff = 0x4567
_getKey = 0x495D
_SendUSBData = 0x50D4
_KillUSBDevice = 0x5236
_KillUSB = 0x810E

appData = 0x08000
curRow = 0x08459
OP1 = 0x084AE
pagedCount = 0x09E15
appBackUpScreen = 0x0A0B0 ; note: this might be wrong
userMem = 0x0A60B

outPageNum = appBackUpScreen+50
usbReadCount = 0x09F61
usbQueuedCount = 0x09F08

.macro SAVE_MEM_PAGE
        in a,(0x0E)
        push af
        in a,(6)
        push af
.endm
.macro RESTORE_MEM_PAGE
        pop af
        out (6),a
        pop af
        out (0x0E),a
.endm
.macro RESTORE_MEM_PAGE_SAVEF
        pop bc
        ld a,b
        out (6),a
        pop bc
        ld a,b
        out (0x0E),a
.endm
.macro SET_FLASH_PAGE_A
        rlca
        out (0x0E),a
        srl a
        out (6),a
.endm
.endif

appTextSave = 1
appFlags = 0x0D

onInterrupt = 4
onFlags = 0x9
LlBrack = 0x0C1

PACKET_SIZE = 1024
CMD_READY = 0x0AA55
CMD_OK = 0x0001
CMD_EXIT = 0x0002
CMD_SIZE = 0x0003
CMD_GETDATA = 0x0005
CMD_DATA = 0x0006
CMD_REPEAT = 0x0007

SPbackup = appBackUpScreen
outputBuffer = appBackUpScreen+2

	;; Loading address, read by the linker script (ldscript).
	.globl __load_addr
__load_addr = userMem - 2

.ifdef TI84P
        .byte 0x0BB,0x6D
.endif
.ifdef TI84PC
        .byte 0x0EF,0x69
        res appTextSave,(iy+appFlags)
        ld a,1
        out (0x20),a
.endif
        B_CALL _runIndicOff
; Unlock Flash, if possible.
; The purpose is to get an accurate dump of the certificate page (page 0x3E/0x7E).
.ifdef TI84P
        in a,(6)
        push af
        call Unlock
        pop af
        out (6),a
.endif

        ld (SPbackup),sp
        call clearScreen
        call IsUSBAvailable
        jr nc,startDump
        call InitializePeriphUSB
        jr nc,startDump
throwError:
        ld sp,(SPbackup)
        call clearScreen
        ld hl,sError
        B_CALL _PutS
        B_CALL _getKey
clearScreen:
        B_CALL _clrLCDFull
        B_CALL _homeUp
        res onInterrupt,(iy+onFlags)
        ret
startDump:
        ld hl,sMessage
        B_CALL _PutS
        res 5,(iy+0x41)
getCommandsLoop:
        ld hl,appData
        call GetPacket
        jr c,throwError
        ld hl,(appData)
;Exit dumper?
        ld de,CMD_EXIT
        B_CALL _cphlde
        jr z,exitDumper
;Requesting ROM dump size?
        ld de,CMD_SIZE
        B_CALL _cphlde
        jr z,sizeRequested
;Requesting ROM data?
        ld de,CMD_GETDATA
        B_CALL _cphlde
        jr z,dataRequested
;Are we ready?
        ld de,CMD_READY
        B_CALL _cphlde
        jr z,readyReceived
        jr getCommandsLoop

exitDumper:
        ld de,CMD_EXIT
        ld bc,0
        call SendPacket
        jr clearScreen

sizeRequested:
        ld hl,outputBuffer
        ld (hl),0
        inc hl
        ld (hl),0
        inc hl
.ifdef TI84PC
        ld (hl),0x40
.else
        in a,(0x21)
        and 3
        ld a,0x10
        jr z,srIsNotSE
        add a,a
srIsNotSE:
        ld (hl),a
.endif
        inc hl
        ld (hl),0
        ld a,0x81
        ld hl,outputBuffer-0x4000
        ld de,CMD_SIZE
        ld bc,4
        call SendPacket
        jp c,throwError
        jr getCommandsLoop

readyReceived:
        ld de,CMD_OK
        ld bc,0
        call SendPacket
        jp c,throwError
        jr getCommandsLoop

dataRequested:
        ld ix,appData+4
        ld l,(ix+0)
        ld h,(ix+1)
        ld e,(ix+2)
        ld d,(ix+3)
        ;DEHL contains the base address
        ld bc,0x0402
        ld (curRow),bc
        ld a,e
        call DispHexA
        ld a,h
        call DispHexA
        ld a,l
        call DispHexA
        ;Figure out what Flash page this is
        ld a,e
        add a,a
        add a,a
drGetFlashPage:
        ld de,0x4000
        or a
        sbc hl,de
        jr c,drGFPDone
        inc a
        jr drGetFlashPage
drGFPDone:
        add hl,de
        ld de,0x4000
        add hl,de
        ;See if this block is "empty"/same
        push hl
        ld (outPageNum),a
        SAVE_MEM_PAGE
        ld a,(outPageNum)
        SET_FLASH_PAGE_A
        ld d,(hl)
        ld bc,PACKET_SIZE
drGFDLoop:
        ld a,(hl)
        cp d
        jr nz,drGFDDone
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,drGFDLoop
drGFDDone:
        RESTORE_MEM_PAGE_SAVEF
        pop hl
        jr z,requestingEmptyPacket
        ld a,(outPageNum)
        ld de,CMD_DATA
        ld bc,PACKET_SIZE
        call SendFlashPacket
        jp c,throwError
        jp getCommandsLoop
requestingEmptyPacket:
        ld ix,OP1
        ld (ix+0),PACKET_SIZE & 0x0FF
        ld (ix+1),(PACKET_SIZE & 0x0FF00) >> 8
        ld (ix+2),d
        ld (ix+3),d
        ld a,0x81
        ld hl,OP1-0x4000
        ld de,CMD_REPEAT
        ld bc,4
        call SendPacket
        jp c,throwError
        jp getCommandsLoop

sMessage:
        .ascii "Dumping"
        .byte 0x0CE
        .ascii "        "
        .ascii "                "
        .ascii "                "
        .ascii "                "
        .ascii "Press "
        .byte LlBrack
        .ascii "ON] to   "
        .asciz "abort."
sError:
        .ascii "ERROR!          "
        .ascii "                "
        .ascii "There was an    "
        .ascii "unknown USB     "
        .ascii "error.          "
        .ascii "                "
        .ascii "Press any key to"
        .asciz "quit."
SendFlashPacket:
.ifdef TI84PC
        rlca
        srl a
.endif
SendPacket:
;Sends a TiLP ROM dump packet.
;Inputs:        DE: command ID
;               HL => buffer of data to send (if any) (0x4000 range)
;               A: page of data to send (if any) (0x81\0x80 for RAM)
;               BC: number of bytes to send
;Outputs:       Returns carry flag set if problems
;Notes:         This routine is absolutely horrible. Somebody optimize it.
        di
        push bc
        ld (outPageNum),a
        SAVE_MEM_PAGE
.ifdef TI84PC
        sbc a,a
        out (0x0E),a
.endif
        ld a,0x83
        out (6),a
        push hl
        ld hl,0x4000
        ld (hl),e
        inc hl
        ld (hl),d
        inc hl
        ld (hl),c
        inc hl
        ld (hl),b
        inc hl
        ex de,hl
        pop hl
        ;Copy BC bytes from HL to DE
        ld a,b
        or c
        jr z,spSkipData
        push bc
spCopyLoop:
        ld a,(outPageNum)
        out (6),a
        ld a,(hl)
        push af
        ld a,0x83
        out (6),a
        pop af
        ld (de),a
        inc hl
        bit 7,h
        jr z,spNC
        res 7,h
        set 6,h
        ld a,(outPageNum)
        inc a
        ld (outPageNum),a
spNC:   inc de
        dec bc
        ld a,b
        or c
        jr nz,spCopyLoop
        pop bc
spSkipData:
        ;Calculate the checksum
        inc bc
        inc bc
        inc bc
        inc bc
        ;Total BC bytes from 0x8000
        ld hl,0x4000
        ld de,0
spGetChecksum:
        ld a,(hl)
        inc hl
        add a,e
        ld e,a
        jr nc,spGCC
        inc d
spGCC:  dec bc
        ld a,b
        or c
        jr nz,spGetChecksum
        ld (hl),e
        inc hl
        ld (hl),d
        RESTORE_MEM_PAGE
        pop de
        inc de
        inc de
        inc de
        inc de
        inc de
        inc de
        ld hl,0x8000
        jp SendUSBData

GetPacket:
;Gets a TiLP ROM dump packet.
;Inputs:        HL points to packet buffer
;Outputs:       Returns carry flag set if problems
        ;Get command and data length words
        ld bc,4
        push hl
        call ReceiveUSBDataWait
        pop hl
        ret c
        inc hl
        inc hl
        ld c,(hl)
        inc hl
        ld b,(hl)
        inc hl
        ld a,b
        or c
        jr z,gpSkipData
        push hl
        push bc
        ;Data bytes
        call ReceiveUSBDataWait
        pop bc
        pop hl
        ret c
        add hl,bc
gpSkipData:
        ;Checksum word
        ld bc,2
        jp ReceiveUSBDataWait
        ;TODO: validate the PC's checksum?

DispHexA:
        push ix
        push af
        push hl
        push bc
        push af
        rrca
        rrca
        rrca
        rrca
        call vdispha
        pop af
        call vdispha
        pop bc
        pop hl
        pop af
        pop ix
        ret
vdispha:
        and 15
        cp 10
        jr nc,vdhlet
        add a,48
        jr vdispd
vdhlet: add a,55
vdispd: B_CALL _PutC
        ret

;----------------------------------------------------------------------------
;InitializePeriphUSB:
;Initializes ourself as a USB peripheral connected to...something.
;Inputs:        None
;Outputs:       Carry flag set if any issues
InitializePeriphUSB:
        B_CALL _KillUSB
        ret c
        ld a,0x80
        out (0x57),a
        xor a
        out (0x4C),a
        ld a,1
        out (0x5B),a
        xor a
        in a,(0x4C)
        ld a,2
        out (0x54),a
        ld a,0x20
        out (0x4A),a
        xor a
        out (0x4B),a
        in a,(0x3A)
        bit 3,a
        jr z,port3AhReset1
        ld a,0x20
        out (0x4B),a
port3AhReset1:
        xor a
        out (0x54),a
        ld a,0x42
        out (0x36),a
        xor a
        out (0x37),a
        ld a,1
        out (0x38),a
timerWait:
        in a,(4)
        bit 7,a
        jr z,timerWait
        in a,(0x3A)
        bit 3,a
        jr z,port3AhReset2
        ld a,0x44
        out (0x54),a
port3AhReset2:
        ld a,0x0C4
        out (0x54),a
        ld a,8
        out (0x4C),a
        ld de,0x0FFFF
port5AhLoop:
        dec de
        ld a,d
        or e
        scf
        ret z
        in a,(0x4C)
        cp 0x1A
        jr z,port5AhDone
        cp 0x5A
        jr nz,port5AhLoop
port5AhDone:
        ld a,0x0FF
        out (0x87),a
        xor a
        out (0x92),a
        in a,(0x87)
        ld a,0x0E
        out (0x89),a
        ld a,5
        out (0x8B),a
        in a,(0x81)
        or 0
        out (0x81),a
        in a,(0x54)
        or 1
        out (0x54),a
        ld b,5
frameCounterLoop:
        ld de,0x0FFFF
frameCounterLoop2:
        dec de
        ld a,d
        or e
        jr z,counterExpired
        in a,(0x8C)
        or a
        jr z,frameCounterLoop2
        ret
counterExpired:
        djnz frameCounterLoop
        scf
        ret

;----------------------------------------------------------------------------
;IsUSBAvailable:
;Returns whether USB communication MAY be available.
;Inputs:        None
;Outputs:       Carry flag set if USB is not available
IsUSBAvailable:
        in a,(2)
        bit 5,a
        scf
        ret z
        ld a,(0x4D)
        or a
        bit 5,a
        ret z
        bit 6,a
        scf
        ret nz
        ccf
        ret

;----------------------------------------------------------------------------
;SendUSBData:
;Sends data over USB.
;Inputs:        HL => data to send
;               DE: number of bytes to send
;Outputs:       DE bytes sent from HL
;               Carry flag set if any issues
SendUSBData:
        set 2,(iy+0x40)
        res 0,(iy+0x43)
        B_CALL _SendUSBData
        res 0,(iy+0x41)
        ret

;----------------------------------------------------------------------------
;ReceiveUSBDataWait:
;Receives data over USB (waits until data is received).
;Inputs:        HL => buffer to store data to
;               BC: number of bytes to receive
;Outputs:       BC bytes received to HL
;               Carry flag set if any issues
;Make sure you know how much you need to be receiving before calling.
;This is a blocking call and will not return until everything is received.
ReceiveUSBDataWait:
        ei
        halt
        in a,(4)
        bit 3,a
        scf
        ret z
        bit 5,(iy+0x41)
        jr z,ReceiveUSBDataWait

;----------------------------------------------------------------------------
;ReceiveUSBData:
;Receives data over USB.
;Inputs:        5,(iy+0x41) set by OS.
;               HL => buffer to store data to
;               BC: number of bytes to receive
;Outputs:       BC bytes received to HL
;               Carry flag set if any issues
;Make sure you know how much you need to be receiving before calling.
ReceiveUSBData:
        push bc
        push af
        xor a
        ld (pagedCount),a
        jr receive_data_ready
receive_big_loop:
        in a,(4)
        bit 3,a
        jr z,P2scfRet
        bit 5,(iy+0x41)
        jr nz,receive_data_ready
        in a,(0x84)
        bit 2,a
        jr nz,receiving_data
        bit 1,a
        jr z,restart_receive_loop
receiving_data:
        set 5,(iy+0x41)
        xor a
        ld (usbQueuedCount),a
        jr receive_data_ready
restart_receive_loop:
        in a,(0x86)
        bit 5,a
        jr nz,P2scfRet
        jr receive_big_loop
receive_data_ready:
        push bc
        push hl
        ld hl,0x40
        or a
        sbc hl,bc
        pop hl
        ld b,c
        jr nc,receiveRest
        ld b,0x40
receiveRest:
        call ReceiveUSBData_small
        ex de,hl
        pop hl
        jr c,P2scfRet
        or a
        ld b,0
        sbc hl,bc
        jr z,P2ret
        ld b,h
        ld c,l
        ex de,hl
        jr receive_big_loop
P2ret:  pop bc
        ld a,b
        pop bc
        ret
P2scfRet:
        pop af
        pop bc
        scf
        ret
ReceiveUSBData_small:
        ld a,b
        or a
        ret z
        ld a,0x40
        cp b
        ret c
        ld a,b
        ld (usbReadCount),a
        ld a,(usbQueuedCount)
        or a
        jr z,ReceiveUSBData_continue
        cp b
        jr nc,ReceiveUSBData_continue
        ld b,a
        ld (usbReadCount),a
ReceiveUSBData_continue:
        in a,(0x8F)
        bit 2,a
        jp z,calcIsPeripheral
        xor a
        out (0x5B),a
        ld a,(usbQueuedCount)
        or a
        jr nz,startReceive
        ld a,1
        out (0x8E),a
        ld a,0x21
        out (0x9A),a
        xor a
        in a,(0x9A)
        ld a,8
        out (0x93),a
        xor a
        in a,(0x93)
        ld a,0x0FF
        out (0x89),a
        xor a
        out (0x95),a
        in a,(0x89)
        ld a,0x0A1
        out (0x8B),a
        in a,(0x94)
        bit 2,a
        jp nz,receiveError
        bit 6,a
        jp nz,receiveError
        ld a,1
        out (0x5B),a
        ld a,(usbQueuedCount)
        or a
        jr nz,startReceive
        ld a,1
        out (0x8E),a
        in a,(0x94)
        in a,(0x96)
startReceive:
        push af
        ld a,(usbReadCount)
        ld b,a
        ld c,0
receiveLoop:
        in a,(0x0A1)
        ld (hl),a
        inc hl
        inc c
        djnz receiveLoop
        ld a,1
        out (0x8E),a
        in a,(0x94)
        bit 2,a
        jr nz,p1ReceiveError
        bit 6,a
        jr nz,p1ReceiveError
        pop af
        sub c
        ld (usbQueuedCount),a
        set 5,(iy+0x41)
        ret nz
        ld a,1
        out (0x8E),a
        ld a,0x21
        out (0x9A),a
        ld a,8
        out (0x93),a
        xor a
        in a,(0x93)
        ld a,0x0E
        out (0x89),a
        xor a
        out (0x95),a
        res 5,(iy+0x41)
        xor a
        ld (usbQueuedCount),a
        res 0,(iy+0x41)
        ld a,0x20
        out (0x94),a
        ld a,1
        out (0x5B),a
        ret
calcIsPeripheral:
        ld a,2
        out (0x8E),a
        in a,(0x94)
        bit 6,a
        jr z,startReceive2
        and 0x0DF
        out (0x94),a
        pop af
        B_CALL _KillUSBDevice
        jr receiveError
startReceive2:
        ld a,(usbQueuedCount)
        or a
        jr nz,startReceive3
        in a,(0x96)
startReceive3:
        push af
        ld c,0
receivePeriphLoop:
        in a,(0x0A2)
        ld (hl),a
        inc hl
        inc c
        djnz receivePeriphLoop
        ld a,2
        out (0x8E),a
        pop af
        sub c
        ld (usbQueuedCount),a
        ret nz
        xor a
        ld (usbQueuedCount),a
        in a,(0x94)
        and 0x0FE
        out (0x94),a
        res 5,(iy+0x41)
        ld a,0x0A1
        ld (0x8B),a
        jr endReceive
p1ReceiveError:
        pop af
receiveError:
        res 5,(iy+0x41)
        scf
endReceive:
        ei
        ld a,1
        out (0x5B),a
        res 0,(iy+0x41)
        ret

;----------------------------------------------------------------------------

.ifdef TI84P

;;; Table of supported OS and boot code versions
VersionTable:
        .byte 1,19, 1,01           ; TI-83 Plus
        .byte 1,19, 1,00           ; TI-83 Plus SE
        .byte 2,55, 1,03           ; TI-84 Plus
        .byte 2,55, 1,03           ; TI-84 Plus SE (odd versions)
        .byte 2,56, 1,03           ; Nspire (even versions)

;; Unlock:
;;
;; Write-enable Flash.
;;
;; Output:
;; - Carry flag set if unlocking failed
;;
;; Destroys:
;; - AF, BC, DE, HL
;; - Port 6
;; - Interrupts disabled
;; - Interrupt mode set to 1

Unlock:
        ;; Check if current OS/boot version is known to be supported
        B_CALL _GetBaseVer
        ld c, a
        B_CALL _GetHWVer
        ld l, a
        add a, -4
        ret c
        inc a
        jr nz, Unlock_NotNspire
        bit 0, b
        jr nz, Unlock_NotNspire
        inc l
Unlock_NotNspire:
        ld h, 0
        add hl, hl
        add hl, hl
        ld de, VersionTable
        add hl, de
        ld a, c
        call CheckVersion
        ret c
        inc hl
        B_CALL _GetBootVer
        call CheckVersion
        ret c

        di
        push iy
         ld de, 0x7B09
         ld a, e
         ld (arcInfo), a
         out (6), a
         ld a, (de)
         ld b, a
         push bc
          push de
           call SetFlashPageD
           ld a, e
           B_CALL _WriteAByteSafe
           ld hl, Unlock_Recover - 2
           ld de, pagedBuf - 2
           B_CALL _Mov18B
           ld (pagedBuf + 2), sp
           call Unlock_Main
           pop af
          pop bc
         jr Unlock_Done

Unlock_Main:
        ld a, (_GetVariableData + 2)
        ld d, a
        ld hl, ramCode
        ld bc, 304
Unlock_Loop1:
        ld a, 0x0ED
        cpir
        ret nz
        ld a, (hl)
        sub 0x0A0
        jr nz, Unlock_Loop1
        ld c, (hl)
        ld b, a
        inc hl
        ld (iMathPtr5), hl
        ld hl, (_GetVariableData)
        inc a
Unlock_Data:
        ld (pagedCount), a
        or a
        call nz, SetFlashPageD
Unlock_Loop2:
        ld a, 0x3A
        cpir
        ret nz
        ld de, Unlock_Data + 1
Unlock_Loop3:
        ld a,(de)
        cp (hl)
        jr nz, Unlock_Loop2
        inc hl
        inc de
        cp 0x0C4
        jr nz, Unlock_Loop3
        B_CALL _LdHLind
        ld iy, 0x56 - 0x25
Unlock_Recover:
        jp (hl)
           ld sp, 0
           pop hl
          pop af
         ld (hl), a
Unlock_WriteByte:
         cp (hl)
         jr nz, Unlock_WriteByte
         ld (hl), 0x0F0
Unlock_Done:
         pop iy
        ret

SetFlashPageD:
        in a, (2)
        add a, a
        ld a, 0x1F
        jr nc, SetFlashPage_Mask
        in a, (0x21)
        and 3
        ld a, 0x7F
        jr nz, SetFlashPage_Mask
        rra
SetFlashPage_Mask:
        and d
        out (6), a
        ret

CheckVersion:
        cp (hl)
        inc hl
        ccf
        ret nz
        ld a, (hl)
        cp b
        ret

.endif
