macro(try_static_libs_if_needed)
    if (TRY_STATIC_LIBS)
        if(APPLE)
            set(DYNAMIC_LIB_EXT ".dylib")
            set(STATIC_LIB_EXT ".a")
            list(APPEND DEPS_LIBRARY_DIRS "/usr/lib/")
        elseif(UNIX)
            set(DYNAMIC_LIB_EXT ".so")
            set(STATIC_LIB_EXT ".a")
            list(APPEND DEPS_LIBRARY_DIRS "/usr/lib/" "/usr/lib64/")
        elseif(WIN32 OR MINGW)
            set(DYNAMIC_LIB_EXT ".dll")
            set(STATIC_LIB_EXT ".lib")
        endif()
        set(TRY_STATIC_DEPS_LDFLAGS "")
        foreach(LIB_NAME ${DEPS_STATIC_LIBRARIES})
            foreach(LIB_DIR ${DEPS_STATIC_LIBRARY_DIRS})
                set(LIB_FULLPATH "${LIB_DIR}/lib${LIB_NAME}${STATIC_LIB_EXT}")
                if(EXISTS ${LIB_FULLPATH})
                    list(APPEND TRY_STATIC_DEPS_LDFLAGS ${LIB_FULLPATH})
                    set(${LIB_NAME}_FOUND YES)
                    break()
                endif()
            endforeach()
            if(NOT ${LIB_NAME}_FOUND)
                foreach(LIB_DIR ${DEPS_LIBRARY_DIRS})
                    set(LIB_FULLPATH "${LIB_DIR}/lib${LIB_NAME}${DYNAMIC_LIB_EXT}")
                    if(EXISTS ${LIB_FULLPATH})
                        list(PREPEND TRY_STATIC_DEPS_LDFLAGS "-l${LIB_NAME}")
                        set(${LIB_NAME}_FOUND YES)
                        message("[Warning] Could not find static lib '${LIB_NAME}' for '${PROJECT_NAME}', using shared lib instead.")
                        break()
                    endif()
                endforeach()
                if(NOT ${LIB_NAME}_FOUND)
                    set(FALLBACK_${LIB_NAME}_STATIC_PATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/lib${LIB_NAME}${STATIC_LIB_EXT}")
                    message("[Warning] Could not find static nor shared lib '${LIB_NAME}' for '${PROJECT_NAME}'! Will assume to be ${FALLBACK_${LIB_NAME}_STATIC_PATH}.")
                    list(APPEND TRY_STATIC_DEPS_LDFLAGS "${FALLBACK_${LIB_NAME}_STATIC_PATH}")
                endif()
            endif()
        endforeach()
        foreach(LIB_DIR ${DEPS_LIBRARY_DIRS})
            list(APPEND TRY_STATIC_DEPS_LDFLAGS "-L${LIB_DIR}")
        endforeach()
        string(REPLACE ";" " " DEPS_STATIC_LDFLAGS_OTHER "${DEPS_STATIC_LDFLAGS_OTHER}")
        list(APPEND TRY_STATIC_DEPS_LDFLAGS "${DEPS_STATIC_LDFLAGS_OTHER}")
    endif()
endmacro()
